# Generated by Django 2.0.3 on 2018-04-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180402_1916'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('from_user', 'to_user')},
        ),
    ]
