# Generated by Django 2.0.3 on 2018-03-30 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_team_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(through='teams.PlayerShip', to=settings.AUTH_USER_MODEL, verbose_name='Players'),
        ),
        migrations.AddField(
            model_name='playership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='playership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
