# Generated by Django 2.0.3 on 2018-03-30 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180330_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(through='teams.PlayerShip', to=settings.AUTH_USER_MODEL),
        ),
    ]
